### ISSUE TITLE
Incompatible md emojis with intercom

### ISSUE THREAD

**Issue by DevJelle** [hotspotty/documentation#18]
Emojis used in the documentation cannot be imported to intercom. Looking into a fix.

**Comment by dansku** [comment]
Is it emojis or the icons? 
In the docs we use <svg> with html. maybe we could use images for those parts?

**Comment by DevJelle** [comment]
Sorry, I should have called this issue differently. The emojis are fine. This is what I can't import:
Docs : ![image](https://user-images.githubusercontent.com/80703032/148640368-a8a7def5-377e-4a57-adc8-77476123a145.png)
Intercom: ![image](https://user-images.githubusercontent.com/80703032/148640384-b1c5880e-c171-47f2-8056-92222af825d2.png)

**Comment by DevJelle** [comment]
Not using Intercom anymore for documentation.
